---
- name: Include variables specific for the distribution.
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- include_tasks: install.yml
- include_tasks: configure.yml
